# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  detect-failed-job:
    runs-on: ubuntu-latest
    steps:
      - name: print failed job
        run: echo "this is first job"

  calling_another:
    needs: detect-failed-job
    uses: ./.github/workflows/second.yml
    
      
